[package]

name = "minigame"
version = "0.1.0"
authors = [ "Valerio Santinelli <santinelli@gmail.com>" ]

[dependencies]
dynamic_reload = {version = "0.2.1", optional=true}
sdl2 = "0.30"

[features]
hotload = ["dynamic_reload"]
default = ["hotload"]
